name: OrgaSegment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.10
  - ipykernel=5.5.5
  - pylint=2.8.3
  - pip=21.1.2
  - tensorflow-gpu=1.15.0
  - keras=2.4.3
  - numpy=1.19.5
  - scipy=1.6.3
  - cython
  - scikit-image=0.18.1
  - h5py
  - imgaug
  - natsort=7.1.1
  - pillow
  - matplotlib=3.4.2
  - pip:
    - git+https://github.com/UMCU-BeekmanLab/Mask_RCNN.git
    - opencv-python==4.5.2.54