name: OrgaSegment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip:
    - scipy=1.11.4
    - ipython=8.18.1
    - matplotlib=3.8.2
    - trackpy=0.6.1
    - natsort=8.4.0
    - opencv-python=4.8.1.78
    - scikit-image=0.22.0
    - numba=0.58.1
    - trackpy=0.5.0
    - scipy=1.5.3
    - streamlit=1.8.1
    - tensorflow[and-cuda]
    - altair=4.0.0
