name: OrgaSegment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6.13
  - ipykernel=5.5.5
  - pylint=2.9.0
  - pip
  - tensorflow-gpu=1.15.0
  - keras=2.3.1
  - numpy=1.19.5
  - scipy=1.5.3
  - cython
  - scikit-image
  - h5py=3.1.0
  - imgaug
  - natsort
  - pillow
  - matplotlib
  - pip:
   - git+https://github.com/UMCU-BeekmanLab/Mask_RCNN.git
   - opencv-python