name: OrgaSegment-mlflow
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip=22.3.1
  - pip:
    - mlflow==2.14.1
    - scipy==1.13.1
    - ipython==8.18.1
    - matplotlib==3.8.2
    - natsort==8.4.0
    - opencv-python==4.8.1.78
    - scikit-image==0.22.0
    - numba==0.58.1
    - keras
    - tensorflow[and-cuda]==2.13.1
    - altair==4.0.0