name: OrgaSegment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - ipykernel=5.3.4
  - pip=21.1.2
  - pylint=2.8.3
  - numpy=1.19.5
  - natsort=7.1.1
  - tifffile
  - opencv
  # - numpy=1.20.2
  # - pandas=1.2.3
  # - scipy=1.6.2
  # - natsort=7.1.1
  # - tqdm=4.59.0
  # - numba=0.53.1
  # - matplotlib=3.3.4
  # - imageio=2.9.0
  # - trackpy=0.4.2
  - pip:
    - tensorflow-gpu==2.5.0
    - keras-unet-collection==0.1.8
  #   - argschema==2.0.2
    # - cellpose==0.6.1 --install-option="--no-deps"