name: OrgaSegment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6.13
  - ipykernel=5.5.5
  - pylint=2.9.0
  - pip=21.1.3
  - tensorflow-gpu=1.15.0
  - keras=2.2.5
  - numpy=1.19.5
  - scipy=1.5.3
  - cython=0.29.23
  - scikit-image=0.17.2
  - h5py=3.1.0
  - imgaug=0.4.0
  - natsort=7.1.1
  - pillow=8.2.0
  - matplotlib=3.3.4
  - pip:
    - git+https://github.com/UMCU-BeekmanLab/Mask_RCNN.git
    - opencv-python==4.5.2.54
