name: OrgaSegment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - ipykernel=5.3.4
  - pip=21.1.2
  - tensorflow-gpu=2.4.1
  - keras=2.4.3
  - pylint=2.8.3
  - numpy=1.19.5
  - natsort=7.1.1
  - pillow=8.2.0
  - matplotlib=3.4.2
  - pip:
    - keras-unet-collection==0.1.8