name: lint

on: [push]

jobs:
  pylint:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v3
    
    - name: Python Pylint GitHub Action
      run: pylint --rcfile=.pylintrc *.py **/*.py