name: test

on:
  push:
    branches:
      - master
      - publication
  pull_request:
    branches:
      - master
      - publication

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    steps:
    - uses: actions/checkout@v3
        
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: conf/environment.yml
        init-shell: bash powershell
        log-level: info
        cache-environment: true
        post-cleanup: 'all' 

    - name: Pylint
      shell: bash -el {0}
      run: |
        conda info
        pylint --rcfile=.pylintrc *.py **/*.py