name: test

on:
  push:
    branches:
      - master
      - publication
  pull_request:
    branches:
      - master
      - publication

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    steps:
    - uses: actions/checkout@v3
        
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: conf/environment.yml
        post-deinit: false
        cache-env: false
        log-level: info 

    - name: Pylint
      run: |
        conda info
        pylint --rcfile=.pylintrc *.py **/*.py