name: tests

on:
  push:
    branches:
      - master
      - publication
  pull_request:
    branches:
      - master
      - publication

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test

    - name: Install dependencies
      run: |
        conda activate test
        conda install tox-conda tox-gh-actions --channel conda-forge
        conda list
    
    - name: Test with tox
      run: |
        conda actite test
        conda env list
        tox -vv