name: test

on:
  push:
    branches:
      - master
      - publication
  pull_request:
    branches:
      - master
      - publication

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-2019]

    steps:
    - uses: actions/checkout@v3
        
    - name: Install Conda environment with Micromamba LINUX
      if: matrix.platform == 'ubuntu-20.04'
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: conf/environment.yml
        log-level: info
        cache-environment: true
        post-cleanup: 'all' 
 
    - name: Install Conda environment with Micromamba WINDOWS
      if: matrix.platform == 'windows-2019'
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: conf/environment.yml
        log-level: info
        cache-environment: true
        post-cleanup: 'all' 
        create-args: pywinpty>=1.1.0
        init-shell: bash

    - name: Pylint LINUX
      if: matrix.platform == 'ubuntu-20.04'
      run: pylint --rcfile=.pylintrc *.py **/*.py
      shell: micromamba-shell {0}
    
    - name: Pylint WINDOWS
      if: matrix.platform == 'windows-2019'
      run: pylint --rcfile=.pylintrc *.py **/*.py
      shell: bash -el {0}