name: tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        auto-activate-base: false

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -el {0}
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    
    - name: Pylint
      shell: bash -el {0}
      run: |
        pylint **/*.py" --disable=R,C,E0401 --output-format=colorized

    - name: Conda install
      if: github.ref_name == 'master' || github.ref_name == 'publication'  
      shell: bash -el {0}
      run: |
        conda info
        conda env create -f conf/environment.yml

    # - name: Tox Conda Environment
    #   shell: bash -el {0}
    #   run: |
    #     conda info
    #     tox -vv -e conda