name: tests

on:
  push:
    branches:
      - master
      - publication
  pull_request:
    branches:
      - master
      - publication

jobs:
  conda:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: OrgaSegment
        environment-file: conf/environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - run: |
        conda info
        conda list